services:
  front:
    container_name: front-chat
    build:
      context: ./frontend
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - back-chat

  back:
    container_name: back-chat
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:dev
